# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fanuc_m20ia_35m_PID_controller

  fanuc_m20ia_35m_PID_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - fanuc_m20ia_35m_world_to_silder
      - fanuc_m20ia_35m_joint_1
      - fanuc_m20ia_35m_joint_2
      - fanuc_m20ia_35m_joint_3
      - fanuc_m20ia_35m_joint_4
      - fanuc_m20ia_35m_joint_5
      - fanuc_m20ia_35m_joint_6
    action_ns: follow_joint_trajectory