# This file defines additional ros2_control controllers that complement the ones defined in moveit_config.
# These controllers allow to control the fanuc with effort interfaces.
# The launch files are responsible for joining the controllers defined in this file with the ones defined in moveit_config and to start the controller manager.
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    fanuc_m20ia_35m_PID_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fanuc_m20ia_35m_task_space_controller:
      type: task_space_trajectory_controller/TaskSpaceTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fanuc_m20ia_35m_PID_controller:
  ros__parameters:
    joints:
      - fanuc_m20ia_35m_world_to_silder
      - fanuc_m20ia_35m_joint_1
      - fanuc_m20ia_35m_joint_2
      - fanuc_m20ia_35m_joint_3
      - fanuc_m20ia_35m_joint_4
      - fanuc_m20ia_35m_joint_5
      - fanuc_m20ia_35m_joint_6
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    gains:
      fanuc_m20ia_35m_world_to_silder:
        p: 60600.0
        d: 12000.0
        i: 3000.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      fanuc_m20ia_35m_joint_1:
        p: 8250.0
        d: 1000.0
        i: 5500.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      fanuc_m20ia_35m_joint_2:
        p: 2000000.0
        d: 8000.0
        i: 70000.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      fanuc_m20ia_35m_joint_3:
        p: 500000.0
        d: 500.0
        i: 1000.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      fanuc_m20ia_35m_joint_4:
        p: 8000.0
        d: 10.0
        i: 300.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      fanuc_m20ia_35m_joint_5:
        p: 200000.0
        d: 100.0
        i: 5000.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      fanuc_m20ia_35m_joint_6:
        p: 8000.0
        d: 30.0
        i: 100.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false

fanuc_m20ia_35m_task_space_controller:
  ros__parameters:
    robot_base_link: "world"
    end_effector_link: "fanuc_m20ia_35m_drilling_tool"
    joint_model_group_name: "fanuc_m20ia_35m_slider_to_drilling_tool"
    debug: true
    use_nullspace: true
    gains:
      k0: 1.0
      position:
        x: 80.0
        y: 80.0
        z: 80.0
      orientation:
        x: 30.0
        y: 30.0
        z: 30.0