planning_plugin: chomp_interface/CHOMPPlanner
enable_failure_recovery: true
jiggle_fraction: 0.05
request_adapters: >-
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/ResolveConstraintFrames
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints
ridge_factor: 0.01
start_state_max_bounds_error: 0.1

fanuc_m20ia_35m_slider_to_drilling_tool:
  default_planner_config: CHOMP
  enforce_joint_model_state_space: false

fanuc_m20ia_35m_base_to_drilling_tool:
  default_planner_config: CHOMP
  enforce_joint_model_state_space: false

fanuc_m20ia_35m_slider_to_inspection_tool:
  default_planner_config: CHOMP
  enforce_joint_model_state_space: false

fanuc_m20ia_35m_base_to_inspection_tool:
  default_planner_config: CHOMP
  enforce_joint_model_state_space: false