# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  fanuc_m20ia_35m_joint_1:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_m20ia_35m_joint_2:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_m20ia_35m_joint_3:
    has_velocity_limits: true
    max_velocity: 3.4900000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_m20ia_35m_joint_4:
    has_velocity_limits: true
    max_velocity: 6.1100000000000003
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_m20ia_35m_joint_5:
    has_velocity_limits: true
    max_velocity: 6.1100000000000003
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.06
    min_position: -0.42
  fanuc_m20ia_35m_joint_6:
    has_velocity_limits: true
    max_velocity: 6.9800000000000004
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.67
    min_position: -0.37
  fanuc_m20ia_35m_world_to_silder:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.1
    min_position: -2.1