# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    fanuc_m20ia_35m_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fanuc_m20ia_35m_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

fanuc_m20ia_35m_joint_trajectory_controller:
  ros__parameters:
    joints:
      - fanuc_m20ia_35m_world_to_silder
      - fanuc_m20ia_35m_joint_1
      - fanuc_m20ia_35m_joint_2
      - fanuc_m20ia_35m_joint_3
      - fanuc_m20ia_35m_joint_4
      - fanuc_m20ia_35m_joint_5
      - fanuc_m20ia_35m_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

fanuc_m20ia_35m_forward_position_controller:
  ros__parameters:
    joints:
      - fanuc_m20ia_35m_world_to_silder
      - fanuc_m20ia_35m_joint_1
      - fanuc_m20ia_35m_joint_2
      - fanuc_m20ia_35m_joint_3
      - fanuc_m20ia_35m_joint_4
      - fanuc_m20ia_35m_joint_5
      - fanuc_m20ia_35m_joint_6
    interface_name: position